spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.marketplace.admin: DEBUG
    org.hibernate.SQL: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
