spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.marketplace.product: DEBUG
    org.hibernate.SQL: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0

app:
  storage:
    base-path: ${UPLOAD_DIR:./uploads/products}